### ISSUE TITLE
Hiding the Feedback button

### ISSUE THREAD

**Issue by ahabbaba9** [zendesk/rate_my_app_android#10]
### Description
* I'd like to know if there's a way to hide the "No, Send Feedback" button in the dialog
 
### Device information
* Android OS version: 8.0.0
* Compile SDK version: 1.11.0.1
* Build tools version: 27.0.3
* Any other relevant information: 

### Steps to reproduce:
1. Open dialog using RateMyAppDialog.showAlways

**Comment by eepDev** [comment]
Hello again @ahabbaba9,

Only way of doing this would be to extend RateMyAppDialog with your own implementation of it, override [onCreateView()](https://github.com/zendesk/rate_my_app_android/blob/master/ratemyapp/src/main/java/com/zendesk/ratemyapp/RateMyAppDialog.java#L141) and create a new `showAlways()` method that works exactly the same but starts your dialog instead of ours.

Thanks,
Elvis
